export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const INPUT_ARTICLE = 'INPUT_ARTICLE'
export const SELECT_ARTICLE = 'SELECT_ARTICLE'
export const DATE_ARTICLE = 'DATE_ARTICLE'

export const ADD_COMMENT = 'ADD_COMMENT'

export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'